### PR TITLE
V3

### PR DESCRIPTION
**Pull request by silverv**

### CODE REVIEW

**Comment by Linjieqiang** [comment]
Is there any difference in hardware compared to the v2 version?

**Comment by pavel-kirienko** [comment]
@Linjieqiang there is none. This firmware has already been tested against the existing hardware (Holybro Kotleta) with ArduPilot:

https://www.youtube.com/watch?v=wBNh1XV1EMQ

https://www.youtube.com/watch?v=FE_kxwhicWM

**Comment by Linjieqiang** [comment]
So only the firmware supports uavcan v1, the motor control algorithm has not changed much, right?

**Comment by pavel-kirienko** [comment]
@Linjieqiang correct. Also it's Cyphal/CAN, not UAVCAN v1.

**Comment by Linjieqiang** [comment]
Oh. I see. Thanks.

**Pull request closed without merging**
